services:
  - type: web
    name: controle-discursos
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: node
    envVars:
      - key: DB_USER
        fromDatabase:
          name: dbcronometro  # Nome do banco criado no Render
          property: user
      - key: DB_HOST
        fromDatabase:
          name: dbcronometro
          property: host
      - key: DB_NAME
        fromDatabase:
          name: dbcronometro
          property: database
      - key: DB_PASSWORD
        fromDatabase:
          name: dbcronometro
          property: password
      - key: DB_PORT
        value: 5432
      - key: DB_SSL
        value: "true"  # Render exige SSL
      - key: PORT
        value: "10000"  # String é mais seguro para YAML
      - key: NODE_ENV
        value: production